@url = http://127.0.0.1:8080
@username = 8b1d2a0fbcab6df8f7224d8b61bcaf28
@password = e10adc3949ba59abbe56e057f20f883e
@cookie = "8b1d2a0fbcab6df8f7224d8b61bcaf28"
@deviceSerial = ""
@deviceName = ""
@validateCode = ""



// 登入

POST {{url}}/login?username={{username}}&password={{password}} HTTP/1.1


###

//list
POST {{url}}/api/list HTTP/1.1


###

// info
POST {{url}}/api/info?deviceSerial={{deviceSerial}} HTTP/1.1
Content-Type: application/json

{

}
###

// changename

POST {{url}}/api/changename?{{deviceSerial}}&{{deviceName}} HTTP/1.1
Content-Type: application/json

{

}

// encrypt

POST {{url}}/api/encrypt?deviceSerial={{deviceSerial}} HTTP/1.1
Content-Type: application/json

{

}